//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Major_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.transacs = new HashSet<transac>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public int item_price { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<transac> transacs { get; set; }
    }
}
