//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Major_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transac
    {
        public transac()
        {
            this.items = new HashSet<item>();
        }
    
        public int transac_id { get; set; }
    
        public virtual ICollection<item> items { get; set; }
    }
}
